apiVersion: v1
kind: Secret
metadata:
   name: nabhi-env
   annotations:
   description: Configuracion de URLS y DataSource para Nabhi
stringData:
    SRV_PROTOCOL: "http://" 
    SRV_JDB_HOST: "jdb"
    SRV_JDB_PORT: "8080"
    SRV_JDB_PATH: "/jdb"
    SRV_JDB_TKN_USER: "jdb"
    SRV_JDB_TKN_PWD: "123456"
    SRV_JDB_TKN_LOCAL: "jdb"
    SRV_JDB_PRIKEY: "123456"
    SRV_JDB_DB_USERNAME: "ATMCLOUD"
    SRV_JDB_DB_PASSWORD: "U4KnAZ0gY6Qbz_sgY6QQ"
    SRV_JDB_DB_HOST: "172.16.136.241"
    SRV_JDB_DB_PORT: "1640"
    SRV_JDB_DB_INSTANCE: "RED"
    SRV_JDB_DATASOURCE: "java:jboss/datasources/atmcloud"
    SRV_JDB_POOLNAME: "AtmCloud"
    SRV_ISO_HOST: "iso"
    SRV_ISO_PORT: "8080"
    SRV_ISO_PATH: "/iso"
    SRV_ISO_TKN_USER: "iso"
    SRV_ISO_TKN_PWD: "123456"
    SRV_ISO_TKN_LOCAL: "iso"
    SRV_ISO_PRIKEY: "123456"
    SRV_ISO_NODE_NAME: "HISO"
    SRV_JKE_HOST: "jke"
    SRV_JKE_PORT: "8080"
    SRV_JKE_PATH: "/jke"
    SRV_JKE_TKN_USER: "jke"
    SRV_JKE_TKN_PWD: "123456"
    SRV_JKE_TKN_LOCAL: "jke"
    SRV_JKE_PRIKEY: "123456"
    SRV_JKE_NODE_NAME: "MTVK"
    SRV_WDL_HOST: "wdl"
    SRV_WDL_PORT: "8080"
    SRV_WDL_PATH: "/wdl"
    SRV_WDL_TKN_USER: "wdl"
    SRV_WDL_TKN_PWD: "123456"
    SRV_WDL_TKN_LOCAL: "wdl"
    SRV_WDL_PRIKEY: "123456"
    SRV_INQ_HOST: "inq"
    SRV_INQ_PORT: "8080"
    SRV_INQ_PATH: "/inq"
    SRV_INQ_TKN_USER: "inq"
    SRV_INQ_TKN_PWD: "123456"
    SRV_INQ_TKN_LOCAL: "inq"
    SRV_INQ_PRIKEY: "123456"
    SRV_GES_HOST: "ges"
    SRV_GES_PORT: "8080"
    SRV_GES_PATH: "/ges"
    SRV_GES_TKN_USER: "ges"
    SRV_GES_TKN_PWD: "123456"
    SRV_GES_TKN_LOCAL: "ges"
    SRV_GES_PRIKEY: "123456"
    SRV_NCH_HOST: "nch"
    SRV_NCH_PORT: "8080"
    SRV_NCH_PATH: "/nch"
    SRV_NCH_TKN_USER: "nch"
    SRV_NCH_TKN_PWD: "123456"
    SRV_NCH_TKN_LOCAL: "nch"
    SRV_NCH_PRIKEY: "123456"
    SRV_STMT_HOST: "stmt"
    SRV_STMT_PORT: "8080"
    SRV_STMT_PATH: "/stmt"
    SRV_STMT_TKN_USER: "stmt"
    SRV_STMT_TKN_PWD: "123456"
    SRV_STMT_TKN_LOCAL: "stmt"
    SRV_STMT_PRIKEY: "123456"
    SRV_RCPT_HOST: "rcpt"
    SRV_RCPT_PORT: "8080"
    SRV_RCPT_PATH: "/rcpt"
    SRV_RCPT_TKN_USER: "rcpt"
    SRV_RCPT_TKN_PWD: "123456"
    SRV_RCPT_TKN_LOCAL: "rcpt"
    SRV_RCPT_PRIKEY: "123456"
    SRV_ADP_HOST: "adp"
    SRV_ADP_PORT: "8080"
    SRV_ADP_PATH: "/adp"
    SRV_ADP_TKN_USER: "adp"
    SRV_ADP_TKN_PWD: "123456"
    SRV_ADP_TKN_LOCAL: "adp"
    SRV_ADP_PRIKEY: "123456"
    SRV_SRH_HOST: "srh"
    SRV_SRH_PORT: "8080"
    SRV_SRH_PATH: "/srh"
    SRV_SRH_TKN_USER: "srh"
    SRV_SRH_TKN_PWD: "123456"
    SRV_SRH_TKN_LOCAL: "srh"
    SRV_SRH_PRIKEY: "123456"
    SRV_JSE_HOST: "jse"
    SRV_JSE_PORT: "8080"
    SRV_JSE_PATH: "/jse"
    SRV_JSE_TKN_USER: "jse"
    SRV_JSE_TKN_PWD: "123456"
    SRV_JSE_TKN_LOCAL: "jse"
    SRV_JSE_PRIKEY: "123456"
    SRV_REV_HOST: "rev"
    SRV_REV_PORT: "8080"
    SRV_REV_PATH: "/rev"
    SRV_REV_TKN_USER: "rev"
    SRV_REV_TKN_PWD: "123456"
    SRV_REV_TKN_LOCAL: "rev"
    SRV_REV_PRIKEY: "123456"